plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

github: [metadata]

title: Learn From IT
tagline: My daily struggles with code

future: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Brett Koenig"